name: Build and test Python package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  linting:
    name: Linting
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
    steps:
      - uses: actions/checkout@v2
      - name: Install and check with black, pylint and pontos.version
        uses: greenbone/actions/lint-python@v2
        with:
          packages: <FIXME>
          version: ${{ matrix.python-version }}

  test:
    name: Run all tests
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - "3.10"
          - "3.11"
    steps:
      - uses: actions/checkout@v2
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests
        run: poetry run python -m unittest

  codecov:
    name: Upload coverage to codecov.io
    needs: test
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Install and calculate and upload coverage to codecov.io
        uses: greenbone/actions/coverage-python@v2
        with:
          version: 3.10

  build-docs:
    name: Build the documentation
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Install python, poetry and dependencies
        uses: greenbone/actions/poetry@v2
        with:
          version: 3.10
      - name: Build docs
        run: cd docs && poetry run make html
